site_name: EnzyMS LCMS Data Analysis Pipeline
theme:
  name: material
nav:
  - Home: index.md
  - Installation: installation.md
  - Input Files: input_files.md
  - Usage: usage.md
  - Pipeline Steps: pipeline_steps.md
  - Output: output.md
  - mzML Conversion: conversion_to_mzml.md
