# File              : parameters.yaml
# Author            : Ashutosh Kumar <kums@zhaw.ch>
# Date              : 17.01.2024
# Last Modified Date: 07.02.2024
# Last Modified By  : Ashutosh Kumar <kums@zhaw.ch>
# A template you can modify and use as an argument to asari command line
# via `--parameters new_filename.yaml`

project_name: asari_project 
mz_tolerance_ppm: 10
mode: pos
# Below rarely modified
multicores: 4
outdir: output
reference: null
autoheight: true
database_mode: auto
gaussian_shape: 0.3
min_intensity_threshold: 1000
min_peak_height: 10000
min_timepoints: 6
rt_align_method: lowess
rt_align_on: true
rtime_tolerance: 50
signal_noise_ratio: 5
wlen: 25
