# File              : parameters.yaml
# Author            : Ashutosh Kumar <kums@zhaw.ch>
# Date              : 19.03.2025
# Last Modified Date: 19.03.2025
# Last Modified By  : Ashutosh Kumar <kums@zhaw.ch>
# This file contains the parameters for the analysis
# The parameters are used by the main script to process the data

project_name: asari_project
mz_tolerance_ppm: 10
mode: pos
# Below rarely modified
multicores: 4
outdir: output
reference: null
autoheight: true
database_mode: auto
gaussian_shape: 0.3
min_intensity_threshold: 1000
min_peak_height: 10000
min_timepoints: 6
rt_align_method: lowess
rt_align_on: true
rtime_tolerance: 50
signal_noise_ratio: 5
wlen: 25
